server:
  port: 8080

spring:
  application:
    name: jpa-board
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(gxQPI/UE9rqyAKhNB210R2OX2iz+WOjBj+zCZjcjKHJrUfGyY0ZMvsGZ9rjXBeRW3z4s54aajEMxTDhEAy59SBZgnQsVby2L1QyqKx/dh4I=)
    username: ENC(3iDxn/uhMiJr6pqxWyerma//j5d/kNOiBSL6AFUR6hQaKFC6BpfbGJfx1F5eiURj)
    password: ENC(sZFETGUH3t/jNaxJmjaKK9xQmjwMmiNXiTFCcI66udLH3U2w8E80yqzXXvAq4sU6)
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor